CERPA/Models/UserJobsViewmodel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CERPA.Models;

namespace CERPA.Models
{
    public class UserJobsViewmodel
    {
        public ApplicationUser User { get; set; }
        public Job Job { get; set; }

    }
}

CERPA/Controllers/UserJobsController.cs
using CERPA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using System.IO;

namespace CERPA.Controllers
{
    public class UserJobsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: UserJobs
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult EmployeeSearch(string searchTerm)
        {
            List<UserJobsViewmodel> UserJobs = new List<UserJobsViewmodel>();
            var users = db.Users.Where(x => x.UserName.Contains(searchTerm) || searchTerm == null).ToList();
            foreach(var user in users)
            {
                var jobs = db.Jobs.Where(y => y.UserID == user.Id && y.IsConfirmed == true).Select(y => y).ToList();
                foreach(var job in jobs)
                {
                    UserJobs.Add(new UserJobsViewmodel
                    {
                        Job = job,
                        User = user
                    });
                }
            }

            return View(UserJobs);
        }
        public TimeSpan? GetTime(Job job)
        {
            return job.ConfirmedOn - job.Start;
        }
        public TimeSpan? GetRoutedTime(Job job)
        {
            return db.PartProcesses.Where(x => x.PartID == job.PartID).Select(x => x.ProcessTime).First();
        }
        public double GetPercentage(Job job)
        {
            var time = GetTime(job);
            var routedTime = GetRoutedTime(job);
            return ((double)routedTime.Value.Ticks / (double)time.Value.Ticks)*(100);
        }
    }
}

CERPA/Views/UserJobs/EmployeeSearch.cshtml
@model IEnumerable<CERPA.Models.UserJobsViewmodel>

<br /><br />
@using (Html.BeginForm("EmployeeSearch", "UserJobs", FormMethod.Get))
{
    @Html.TextBox("searchTerm")<input type="submit" value="Search" />
}
<table class="table table-striped">
    <thead>
        <tr>
            <th>User Name</th>
            <th>Job Id</th>
            <th>Routed time</th>
            <th>Total time</th>
            <th>Percentage</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count()==0)
        {
            <tr>
                <td colspan="3"  style="color:red">
                    Your search did not return any results.
                </td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
            <tr>
                <td>@item.User.UserName</td>
                <td>@item.Job.ID</td>
                <td>@Html.Action("GetRoutedTime", new{ Job = item.Job})</td>
                <td>@Html.Action("GetTime", new{ Job = item.Job})</td>
                <td>@Html.Action("GetPercentage", new{ Job = item.Job})</td>
            </tr>
            }
        }
    </tbody>
</table>